### PR TITLE
including play in  enviromental varialbe $PATH

### PR DESCRIPTION
**Pull request by EslamElHusseiny**
linking $play_path/play to /usr/bin/play to get play in $PATH

### CODE REVIEW

**Comment by cescoffier** [comment]
I've integrated your pull request (manually). Could you check ? I had to fix a couple of conflicts.

**Comment by EslamElHusseiny** [comment]
you've added unversioned  symlink to the play installation besides play installation, So where's conflict then ?

**Comment by cescoffier** [comment]
I just had another pull request in the mean time. It was a pretty simple conflict, but was not able to test my merge.

**Comment by EslamElHusseiny** [comment]
anyway, it seems you merged my stuff successfully, i'm not sure if  "# Add a unversioned symlink to the play installation." was the other pull request you received or not

**Pull request closed without merging**
